package com.core.model;



public class TWxApp  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_app.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_app.WXID
     *
     * @mbggenerated
     */
    private String wxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_app.WXNAME
     *
     * @mbggenerated
     */
    private String wxname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_app.APPID
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_app.APPSECRET
     *
     * @mbggenerated
     */
    private String appsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_app.TOKEN
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_app.ENCODINGAESKEY
     *
     * @mbggenerated
     */
    private String encodingaeskey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_app.ENCRYPTMESSAGE
     *
     * @mbggenerated
     */
    private String encryptmessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_app
     *
     * @mbggenerated
     */
    public TWxApp(String id, String wxid, String wxname, String appid, String appsecret, String token, String encodingaeskey, String encryptmessage) {
        this.id = id;
        this.wxid = wxid;
        this.wxname = wxname;
        this.appid = appid;
        this.appsecret = appsecret;
        this.token = token;
        this.encodingaeskey = encodingaeskey;
        this.encryptmessage = encryptmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_app.ID
     *
     * @return the value of t_wx_app.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_app.WXID
     *
     * @return the value of t_wx_app.WXID
     *
     * @mbggenerated
     */
    public String getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_app.WXNAME
     *
     * @return the value of t_wx_app.WXNAME
     *
     * @mbggenerated
     */
    public String getWxname() {
        return wxname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_app.APPID
     *
     * @return the value of t_wx_app.APPID
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_app.APPSECRET
     *
     * @return the value of t_wx_app.APPSECRET
     *
     * @mbggenerated
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_app.TOKEN
     *
     * @return the value of t_wx_app.TOKEN
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_app.ENCODINGAESKEY
     *
     * @return the value of t_wx_app.ENCODINGAESKEY
     *
     * @mbggenerated
     */
    public String getEncodingaeskey() {
        return encodingaeskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_app.ENCRYPTMESSAGE
     *
     * @return the value of t_wx_app.ENCRYPTMESSAGE
     *
     * @mbggenerated
     */
    public String getEncryptmessage() {
        return encryptmessage;
    }
}