package com.core.model;

import java.util.Date;

public class TWxSubs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.APPID
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.OPENID
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.SUBSCRIBETIME
     *
     * @mbggenerated
     */
    private Date subscribetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.NICKNAME
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.USER_LOGIN_NAME
     *
     * @mbggenerated
     */
    private String userLoginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.DEPT_CODE
     *
     * @mbggenerated
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.CITY_CODE
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.COUNTRY_CODE
     *
     * @mbggenerated
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.PROVINCE_CODE
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.LANGUAGE
     *
     * @mbggenerated
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.HEADIMGURL
     *
     * @mbggenerated
     */
    private String headimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.UNIONID
     *
     * @mbggenerated
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_subs. PARENT_ID
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_subs
     *
     * @mbggenerated
     */
    public TWxSubs(String id, String appid, String openid, Date subscribetime, String nickname, String userLoginName, String deptCode, String sex, String cityCode, String countryCode, String provinceCode, String language, String headimgurl, String unionid, Date createTime, Date updateTime, String parentId) {
        this.id = id;
        this.appid = appid;
        this.openid = openid;
        this.subscribetime = subscribetime;
        this.nickname = nickname;
        this.userLoginName = userLoginName;
        this.deptCode = deptCode;
        this.sex = sex;
        this.cityCode = cityCode;
        this.countryCode = countryCode;
        this.provinceCode = provinceCode;
        this.language = language;
        this.headimgurl = headimgurl;
        this.unionid = unionid;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.ID
     *
     * @return the value of t_wx_subs.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.APPID
     *
     * @return the value of t_wx_subs.APPID
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.OPENID
     *
     * @return the value of t_wx_subs.OPENID
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.SUBSCRIBETIME
     *
     * @return the value of t_wx_subs.SUBSCRIBETIME
     *
     * @mbggenerated
     */
    public Date getSubscribetime() {
        return subscribetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.NICKNAME
     *
     * @return the value of t_wx_subs.NICKNAME
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.USER_LOGIN_NAME
     *
     * @return the value of t_wx_subs.USER_LOGIN_NAME
     *
     * @mbggenerated
     */
    public String getUserLoginName() {
        return userLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.DEPT_CODE
     *
     * @return the value of t_wx_subs.DEPT_CODE
     *
     * @mbggenerated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.SEX
     *
     * @return the value of t_wx_subs.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.CITY_CODE
     *
     * @return the value of t_wx_subs.CITY_CODE
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.COUNTRY_CODE
     *
     * @return the value of t_wx_subs.COUNTRY_CODE
     *
     * @mbggenerated
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.PROVINCE_CODE
     *
     * @return the value of t_wx_subs.PROVINCE_CODE
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.LANGUAGE
     *
     * @return the value of t_wx_subs.LANGUAGE
     *
     * @mbggenerated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.HEADIMGURL
     *
     * @return the value of t_wx_subs.HEADIMGURL
     *
     * @mbggenerated
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.UNIONID
     *
     * @return the value of t_wx_subs.UNIONID
     *
     * @mbggenerated
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.CREATE_TIME
     *
     * @return the value of t_wx_subs.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs.UPDATE_TIME
     *
     * @return the value of t_wx_subs.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_subs. PARENT_ID
     *
     * @return the value of t_wx_subs. PARENT_ID
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }
}