package com.core.model;

public class ViewCache {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cache.P_KEY
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    private String pKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cache.p_value
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    private Long pValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cache.p_desc
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    private String pDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_cache.P_P_VALUE
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    private String pPValue;

    public void setpKey(String pKey) {
        this.pKey = pKey;
    }

    public void setpValue(Long pValue) {
        this.pValue = pValue;
    }

    public void setpDesc(String pDesc) {
        this.pDesc = pDesc;
    }

    public void setpPValue(String pPValue) {
        this.pPValue = pPValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cache
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    public ViewCache(String pKey, Long pValue, String pDesc, String pPValue) {
        this.pKey = pKey;
        this.pValue = pValue;
        this.pDesc = pDesc;
        this.pPValue = pPValue;

    }

    public ViewCache() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cache.P_KEY
     *
     * @return the value of view_cache.P_KEY
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    public String getpKey() {
        return pKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cache.p_value
     *
     * @return the value of view_cache.p_value
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    public Long getpValue() {
        return pValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cache.p_desc
     *
     * @return the value of view_cache.p_desc
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    public String getpDesc() {
        return pDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_cache.P_P_VALUE
     *
     * @return the value of view_cache.P_P_VALUE
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    public String getpPValue() {
        return pPValue;
    }
}