package com.core.model;

public class WebsiteArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_area.area_id
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    private Long areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_area.area_name
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_area.parent_id
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_area.area_level
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    private Short areaLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_area.status
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_area.sort_id
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    private Integer sortId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_area
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    public WebsiteArea(Long areaId, String areaName, Long parentId, Short areaLevel, Short status, Integer sortId) {
        this.areaId = areaId;
        this.areaName = areaName;
        this.parentId = parentId;
        this.areaLevel = areaLevel;
        this.status = status;
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_area.area_id
     *
     * @return the value of website_area.area_id
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_area.area_name
     *
     * @return the value of website_area.area_name
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_area.parent_id
     *
     * @return the value of website_area.parent_id
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_area.area_level
     *
     * @return the value of website_area.area_level
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    public Short getAreaLevel() {
        return areaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_area.status
     *
     * @return the value of website_area.status
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_area.sort_id
     *
     * @return the value of website_area.sort_id
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    public Integer getSortId() {
        return sortId;
    }
}