package com.core.model;

public class WxMerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_mer_info.gds_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer gdsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_mer_info.gds_title
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String gdsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_mer_info.gds_description
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String gdsDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_mer_info.gds_price
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer gdsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_mer_info.pic_url
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_mer_info.url
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_mer_info.gds_count
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer gdsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_mer_info.order_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_mer_info.gds_url
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String gdsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_mer_info.gds_detail
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String gdsDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public WxMerInfo(Integer gdsId, String gdsTitle, String gdsDescription, Integer gdsPrice, String picUrl, String url, Integer gdsCount, Integer orderId, String gdsUrl, String gdsDetail) {
        this.gdsId = gdsId;
        this.gdsTitle = gdsTitle;
        this.gdsDescription = gdsDescription;
        this.gdsPrice = gdsPrice;
        this.picUrl = picUrl;
        this.url = url;
        this.gdsCount = gdsCount;
        this.orderId = orderId;
        this.gdsUrl = gdsUrl;
        this.gdsDetail = gdsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_mer_info.gds_id
     *
     * @return the value of wx_mer_info.gds_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getGdsId() {
        return gdsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_mer_info.gds_title
     *
     * @return the value of wx_mer_info.gds_title
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getGdsTitle() {
        return gdsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_mer_info.gds_description
     *
     * @return the value of wx_mer_info.gds_description
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getGdsDescription() {
        return gdsDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_mer_info.gds_price
     *
     * @return the value of wx_mer_info.gds_price
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getGdsPrice() {
        return gdsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_mer_info.pic_url
     *
     * @return the value of wx_mer_info.pic_url
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_mer_info.url
     *
     * @return the value of wx_mer_info.url
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_mer_info.gds_count
     *
     * @return the value of wx_mer_info.gds_count
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getGdsCount() {
        return gdsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_mer_info.order_id
     *
     * @return the value of wx_mer_info.order_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_mer_info.gds_url
     *
     * @return the value of wx_mer_info.gds_url
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getGdsUrl() {
        return gdsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_mer_info.gds_detail
     *
     * @return the value of wx_mer_info.gds_detail
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getGdsDetail() {
        return gdsDetail;
    }
}