package com.core.model;

import java.util.ArrayList;
import java.util.List;

public class WxMerInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public WxMerInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGdsIdIsNull() {
            addCriterion("gds_id is null");
            return (Criteria) this;
        }

        public Criteria andGdsIdIsNotNull() {
            addCriterion("gds_id is not null");
            return (Criteria) this;
        }

        public Criteria andGdsIdEqualTo(Integer value) {
            addCriterion("gds_id =", value, "gdsId");
            return (Criteria) this;
        }

        public Criteria andGdsIdNotEqualTo(Integer value) {
            addCriterion("gds_id <>", value, "gdsId");
            return (Criteria) this;
        }

        public Criteria andGdsIdGreaterThan(Integer value) {
            addCriterion("gds_id >", value, "gdsId");
            return (Criteria) this;
        }

        public Criteria andGdsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("gds_id >=", value, "gdsId");
            return (Criteria) this;
        }

        public Criteria andGdsIdLessThan(Integer value) {
            addCriterion("gds_id <", value, "gdsId");
            return (Criteria) this;
        }

        public Criteria andGdsIdLessThanOrEqualTo(Integer value) {
            addCriterion("gds_id <=", value, "gdsId");
            return (Criteria) this;
        }

        public Criteria andGdsIdIn(List<Integer> values) {
            addCriterion("gds_id in", values, "gdsId");
            return (Criteria) this;
        }

        public Criteria andGdsIdNotIn(List<Integer> values) {
            addCriterion("gds_id not in", values, "gdsId");
            return (Criteria) this;
        }

        public Criteria andGdsIdBetween(Integer value1, Integer value2) {
            addCriterion("gds_id between", value1, value2, "gdsId");
            return (Criteria) this;
        }

        public Criteria andGdsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("gds_id not between", value1, value2, "gdsId");
            return (Criteria) this;
        }

        public Criteria andGdsTitleIsNull() {
            addCriterion("gds_title is null");
            return (Criteria) this;
        }

        public Criteria andGdsTitleIsNotNull() {
            addCriterion("gds_title is not null");
            return (Criteria) this;
        }

        public Criteria andGdsTitleEqualTo(String value) {
            addCriterion("gds_title =", value, "gdsTitle");
            return (Criteria) this;
        }

        public Criteria andGdsTitleNotEqualTo(String value) {
            addCriterion("gds_title <>", value, "gdsTitle");
            return (Criteria) this;
        }

        public Criteria andGdsTitleGreaterThan(String value) {
            addCriterion("gds_title >", value, "gdsTitle");
            return (Criteria) this;
        }

        public Criteria andGdsTitleGreaterThanOrEqualTo(String value) {
            addCriterion("gds_title >=", value, "gdsTitle");
            return (Criteria) this;
        }

        public Criteria andGdsTitleLessThan(String value) {
            addCriterion("gds_title <", value, "gdsTitle");
            return (Criteria) this;
        }

        public Criteria andGdsTitleLessThanOrEqualTo(String value) {
            addCriterion("gds_title <=", value, "gdsTitle");
            return (Criteria) this;
        }

        public Criteria andGdsTitleLike(String value) {
            addCriterion("gds_title like", value, "gdsTitle");
            return (Criteria) this;
        }

        public Criteria andGdsTitleNotLike(String value) {
            addCriterion("gds_title not like", value, "gdsTitle");
            return (Criteria) this;
        }

        public Criteria andGdsTitleIn(List<String> values) {
            addCriterion("gds_title in", values, "gdsTitle");
            return (Criteria) this;
        }

        public Criteria andGdsTitleNotIn(List<String> values) {
            addCriterion("gds_title not in", values, "gdsTitle");
            return (Criteria) this;
        }

        public Criteria andGdsTitleBetween(String value1, String value2) {
            addCriterion("gds_title between", value1, value2, "gdsTitle");
            return (Criteria) this;
        }

        public Criteria andGdsTitleNotBetween(String value1, String value2) {
            addCriterion("gds_title not between", value1, value2, "gdsTitle");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionIsNull() {
            addCriterion("gds_description is null");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionIsNotNull() {
            addCriterion("gds_description is not null");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionEqualTo(String value) {
            addCriterion("gds_description =", value, "gdsDescription");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionNotEqualTo(String value) {
            addCriterion("gds_description <>", value, "gdsDescription");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionGreaterThan(String value) {
            addCriterion("gds_description >", value, "gdsDescription");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("gds_description >=", value, "gdsDescription");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionLessThan(String value) {
            addCriterion("gds_description <", value, "gdsDescription");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionLessThanOrEqualTo(String value) {
            addCriterion("gds_description <=", value, "gdsDescription");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionLike(String value) {
            addCriterion("gds_description like", value, "gdsDescription");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionNotLike(String value) {
            addCriterion("gds_description not like", value, "gdsDescription");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionIn(List<String> values) {
            addCriterion("gds_description in", values, "gdsDescription");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionNotIn(List<String> values) {
            addCriterion("gds_description not in", values, "gdsDescription");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionBetween(String value1, String value2) {
            addCriterion("gds_description between", value1, value2, "gdsDescription");
            return (Criteria) this;
        }

        public Criteria andGdsDescriptionNotBetween(String value1, String value2) {
            addCriterion("gds_description not between", value1, value2, "gdsDescription");
            return (Criteria) this;
        }

        public Criteria andGdsPriceIsNull() {
            addCriterion("gds_price is null");
            return (Criteria) this;
        }

        public Criteria andGdsPriceIsNotNull() {
            addCriterion("gds_price is not null");
            return (Criteria) this;
        }

        public Criteria andGdsPriceEqualTo(Integer value) {
            addCriterion("gds_price =", value, "gdsPrice");
            return (Criteria) this;
        }

        public Criteria andGdsPriceNotEqualTo(Integer value) {
            addCriterion("gds_price <>", value, "gdsPrice");
            return (Criteria) this;
        }

        public Criteria andGdsPriceGreaterThan(Integer value) {
            addCriterion("gds_price >", value, "gdsPrice");
            return (Criteria) this;
        }

        public Criteria andGdsPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("gds_price >=", value, "gdsPrice");
            return (Criteria) this;
        }

        public Criteria andGdsPriceLessThan(Integer value) {
            addCriterion("gds_price <", value, "gdsPrice");
            return (Criteria) this;
        }

        public Criteria andGdsPriceLessThanOrEqualTo(Integer value) {
            addCriterion("gds_price <=", value, "gdsPrice");
            return (Criteria) this;
        }

        public Criteria andGdsPriceIn(List<Integer> values) {
            addCriterion("gds_price in", values, "gdsPrice");
            return (Criteria) this;
        }

        public Criteria andGdsPriceNotIn(List<Integer> values) {
            addCriterion("gds_price not in", values, "gdsPrice");
            return (Criteria) this;
        }

        public Criteria andGdsPriceBetween(Integer value1, Integer value2) {
            addCriterion("gds_price between", value1, value2, "gdsPrice");
            return (Criteria) this;
        }

        public Criteria andGdsPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("gds_price not between", value1, value2, "gdsPrice");
            return (Criteria) this;
        }

        public Criteria andPicUrlIsNull() {
            addCriterion("pic_url is null");
            return (Criteria) this;
        }

        public Criteria andPicUrlIsNotNull() {
            addCriterion("pic_url is not null");
            return (Criteria) this;
        }

        public Criteria andPicUrlEqualTo(String value) {
            addCriterion("pic_url =", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotEqualTo(String value) {
            addCriterion("pic_url <>", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlGreaterThan(String value) {
            addCriterion("pic_url >", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("pic_url >=", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLessThan(String value) {
            addCriterion("pic_url <", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLessThanOrEqualTo(String value) {
            addCriterion("pic_url <=", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLike(String value) {
            addCriterion("pic_url like", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotLike(String value) {
            addCriterion("pic_url not like", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlIn(List<String> values) {
            addCriterion("pic_url in", values, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotIn(List<String> values) {
            addCriterion("pic_url not in", values, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlBetween(String value1, String value2) {
            addCriterion("pic_url between", value1, value2, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotBetween(String value1, String value2) {
            addCriterion("pic_url not between", value1, value2, "picUrl");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andGdsCountIsNull() {
            addCriterion("gds_count is null");
            return (Criteria) this;
        }

        public Criteria andGdsCountIsNotNull() {
            addCriterion("gds_count is not null");
            return (Criteria) this;
        }

        public Criteria andGdsCountEqualTo(Integer value) {
            addCriterion("gds_count =", value, "gdsCount");
            return (Criteria) this;
        }

        public Criteria andGdsCountNotEqualTo(Integer value) {
            addCriterion("gds_count <>", value, "gdsCount");
            return (Criteria) this;
        }

        public Criteria andGdsCountGreaterThan(Integer value) {
            addCriterion("gds_count >", value, "gdsCount");
            return (Criteria) this;
        }

        public Criteria andGdsCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("gds_count >=", value, "gdsCount");
            return (Criteria) this;
        }

        public Criteria andGdsCountLessThan(Integer value) {
            addCriterion("gds_count <", value, "gdsCount");
            return (Criteria) this;
        }

        public Criteria andGdsCountLessThanOrEqualTo(Integer value) {
            addCriterion("gds_count <=", value, "gdsCount");
            return (Criteria) this;
        }

        public Criteria andGdsCountIn(List<Integer> values) {
            addCriterion("gds_count in", values, "gdsCount");
            return (Criteria) this;
        }

        public Criteria andGdsCountNotIn(List<Integer> values) {
            addCriterion("gds_count not in", values, "gdsCount");
            return (Criteria) this;
        }

        public Criteria andGdsCountBetween(Integer value1, Integer value2) {
            addCriterion("gds_count between", value1, value2, "gdsCount");
            return (Criteria) this;
        }

        public Criteria andGdsCountNotBetween(Integer value1, Integer value2) {
            addCriterion("gds_count not between", value1, value2, "gdsCount");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andGdsUrlIsNull() {
            addCriterion("gds_url is null");
            return (Criteria) this;
        }

        public Criteria andGdsUrlIsNotNull() {
            addCriterion("gds_url is not null");
            return (Criteria) this;
        }

        public Criteria andGdsUrlEqualTo(String value) {
            addCriterion("gds_url =", value, "gdsUrl");
            return (Criteria) this;
        }

        public Criteria andGdsUrlNotEqualTo(String value) {
            addCriterion("gds_url <>", value, "gdsUrl");
            return (Criteria) this;
        }

        public Criteria andGdsUrlGreaterThan(String value) {
            addCriterion("gds_url >", value, "gdsUrl");
            return (Criteria) this;
        }

        public Criteria andGdsUrlGreaterThanOrEqualTo(String value) {
            addCriterion("gds_url >=", value, "gdsUrl");
            return (Criteria) this;
        }

        public Criteria andGdsUrlLessThan(String value) {
            addCriterion("gds_url <", value, "gdsUrl");
            return (Criteria) this;
        }

        public Criteria andGdsUrlLessThanOrEqualTo(String value) {
            addCriterion("gds_url <=", value, "gdsUrl");
            return (Criteria) this;
        }

        public Criteria andGdsUrlLike(String value) {
            addCriterion("gds_url like", value, "gdsUrl");
            return (Criteria) this;
        }

        public Criteria andGdsUrlNotLike(String value) {
            addCriterion("gds_url not like", value, "gdsUrl");
            return (Criteria) this;
        }

        public Criteria andGdsUrlIn(List<String> values) {
            addCriterion("gds_url in", values, "gdsUrl");
            return (Criteria) this;
        }

        public Criteria andGdsUrlNotIn(List<String> values) {
            addCriterion("gds_url not in", values, "gdsUrl");
            return (Criteria) this;
        }

        public Criteria andGdsUrlBetween(String value1, String value2) {
            addCriterion("gds_url between", value1, value2, "gdsUrl");
            return (Criteria) this;
        }

        public Criteria andGdsUrlNotBetween(String value1, String value2) {
            addCriterion("gds_url not between", value1, value2, "gdsUrl");
            return (Criteria) this;
        }

        public Criteria andGdsDetailIsNull() {
            addCriterion("gds_detail is null");
            return (Criteria) this;
        }

        public Criteria andGdsDetailIsNotNull() {
            addCriterion("gds_detail is not null");
            return (Criteria) this;
        }

        public Criteria andGdsDetailEqualTo(String value) {
            addCriterion("gds_detail =", value, "gdsDetail");
            return (Criteria) this;
        }

        public Criteria andGdsDetailNotEqualTo(String value) {
            addCriterion("gds_detail <>", value, "gdsDetail");
            return (Criteria) this;
        }

        public Criteria andGdsDetailGreaterThan(String value) {
            addCriterion("gds_detail >", value, "gdsDetail");
            return (Criteria) this;
        }

        public Criteria andGdsDetailGreaterThanOrEqualTo(String value) {
            addCriterion("gds_detail >=", value, "gdsDetail");
            return (Criteria) this;
        }

        public Criteria andGdsDetailLessThan(String value) {
            addCriterion("gds_detail <", value, "gdsDetail");
            return (Criteria) this;
        }

        public Criteria andGdsDetailLessThanOrEqualTo(String value) {
            addCriterion("gds_detail <=", value, "gdsDetail");
            return (Criteria) this;
        }

        public Criteria andGdsDetailLike(String value) {
            addCriterion("gds_detail like", value, "gdsDetail");
            return (Criteria) this;
        }

        public Criteria andGdsDetailNotLike(String value) {
            addCriterion("gds_detail not like", value, "gdsDetail");
            return (Criteria) this;
        }

        public Criteria andGdsDetailIn(List<String> values) {
            addCriterion("gds_detail in", values, "gdsDetail");
            return (Criteria) this;
        }

        public Criteria andGdsDetailNotIn(List<String> values) {
            addCriterion("gds_detail not in", values, "gdsDetail");
            return (Criteria) this;
        }

        public Criteria andGdsDetailBetween(String value1, String value2) {
            addCriterion("gds_detail between", value1, value2, "gdsDetail");
            return (Criteria) this;
        }

        public Criteria andGdsDetailNotBetween(String value1, String value2) {
            addCriterion("gds_detail not between", value1, value2, "gdsDetail");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_mer_info
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 03 21:32:31 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}