package com.core.model;

public class WxOrderAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_address.user_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_address.order_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_address.province
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_address.city
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_address.county
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_address.address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_address.receiver
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_address.mobile_phone
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String mobilePhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public WxOrderAddress(Integer userId, Long orderId, String province, String city, String county, String address, String receiver, String mobilePhone) {
        this.userId = userId;
        this.orderId = orderId;
        this.province = province;
        this.city = city;
        this.county = county;
        this.address = address;
        this.receiver = receiver;
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_address.user_id
     *
     * @return the value of wx_order_address.user_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_address.order_id
     *
     * @return the value of wx_order_address.order_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_address.province
     *
     * @return the value of wx_order_address.province
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_address.city
     *
     * @return the value of wx_order_address.city
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_address.county
     *
     * @return the value of wx_order_address.county
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_address.address
     *
     * @return the value of wx_order_address.address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_address.receiver
     *
     * @return the value of wx_order_address.receiver
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_address.mobile_phone
     *
     * @return the value of wx_order_address.mobile_phone
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getMobilePhone() {
        return mobilePhone;
    }
}