package com.core.model;

import java.util.Date;

public class WxOrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_info.order_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_info.gds_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer gdsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_info.gds_amount
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer gdsAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_info.gds_count
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer gdsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_info.status
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_info.pay_type
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_info.pay_status
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_info.create_time
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_info.remark
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_order_info.user_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public WxOrderInfo(Long orderId, Integer gdsId, Integer gdsAmount, Integer gdsCount, Integer status, String payType, Integer payStatus, Date createTime, String remark, Integer userId) {
        this.orderId = orderId;
        this.gdsId = gdsId;
        this.gdsAmount = gdsAmount;
        this.gdsCount = gdsCount;
        this.status = status;
        this.payType = payType;
        this.payStatus = payStatus;
        this.createTime = createTime;
        this.remark = remark;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_info.order_id
     *
     * @return the value of wx_order_info.order_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_info.gds_id
     *
     * @return the value of wx_order_info.gds_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getGdsId() {
        return gdsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_info.gds_amount
     *
     * @return the value of wx_order_info.gds_amount
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getGdsAmount() {
        return gdsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_info.gds_count
     *
     * @return the value of wx_order_info.gds_count
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getGdsCount() {
        return gdsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_info.status
     *
     * @return the value of wx_order_info.status
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_info.pay_type
     *
     * @return the value of wx_order_info.pay_type
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_info.pay_status
     *
     * @return the value of wx_order_info.pay_status
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_info.create_time
     *
     * @return the value of wx_order_info.create_time
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_info.remark
     *
     * @return the value of wx_order_info.remark
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_order_info.user_id
     *
     * @return the value of wx_order_info.user_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }
}