package com.core.model;

import java.util.Date;

public class WxPayInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_info.pay_no
     *
     * @mbggenerated Sat Nov 28 02:07:34 CST 2015
     */
    private Integer payNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_info.pay_amount
     *
     * @mbggenerated Sat Nov 28 02:07:34 CST 2015
     */
    private Integer payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_info.order_id
     *
     * @mbggenerated Sat Nov 28 02:07:34 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_pay_info.pay_time
     *
     * @mbggenerated Sat Nov 28 02:07:34 CST 2015
     */
    private Date payTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_info
     *
     * @mbggenerated Sat Nov 28 02:07:34 CST 2015
     */
    public WxPayInfo(Integer payNo, Integer payAmount, Long orderId, Date payTime) {
        this.payNo = payNo;
        this.payAmount = payAmount;
        this.orderId = orderId;
        this.payTime = payTime;
    }

    public void setPayNo(Integer payNo) {
        this.payNo = payNo;
    }

    public void setPayAmount(Integer payAmount) {
        this.payAmount = payAmount;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    public WxPayInfo() {

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_info.pay_no
     *
     * @return the value of wx_pay_info.pay_no
     *
     * @mbggenerated Sat Nov 28 02:07:34 CST 2015
     */
    public Integer getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_info.pay_amount
     *
     * @return the value of wx_pay_info.pay_amount
     *
     * @mbggenerated Sat Nov 28 02:07:34 CST 2015
     */
    public Integer getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_info.order_id
     *
     * @return the value of wx_pay_info.order_id
     *
     * @mbggenerated Sat Nov 28 02:07:34 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_pay_info.pay_time
     *
     * @return the value of wx_pay_info.pay_time
     *
     * @mbggenerated Sat Nov 28 02:07:34 CST 2015
     */
    public Date getPayTime() {
        return payTime;
    }
}