package com.core.model;

import java.util.Date;

public class WxUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.user_id
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.open_id
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.nickname
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.sex
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.province
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.city
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.country
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.headimgurl
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    private String headimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.subscribe
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    private Integer subscribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.parentId
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.ticket
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    private String ticket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.createTime
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.commission
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    private Integer commission;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public WxUserInfo(Integer userId, String openId, String nickname, Integer sex, String province, String city, String country, String headimgurl, Integer subscribe, Integer parentid, String ticket, Date createtime, Integer commission) {
        this.userId = userId;
        this.openId = openId;
        this.nickname = nickname;
        this.sex = sex;
        this.province = province;
        this.city = city;
        this.country = country;
        this.headimgurl = headimgurl;
        this.subscribe = subscribe;
        this.parentid = parentid;
        this.ticket = ticket;
        this.createtime = createtime;
        this.commission = commission;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }

    public void setSubscribe(Integer subscribe) {
        this.subscribe = subscribe;
    }

    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    public void setTicket(String ticket) {
        this.ticket = ticket;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public void setCommission(Integer commission) {
        this.commission = commission;
    }

    public WxUserInfo() {

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.user_id
     *
     * @return the value of wx_user_info.user_id
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.open_id
     *
     * @return the value of wx_user_info.open_id
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.nickname
     *
     * @return the value of wx_user_info.nickname
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.sex
     *
     * @return the value of wx_user_info.sex
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.province
     *
     * @return the value of wx_user_info.province
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.city
     *
     * @return the value of wx_user_info.city
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.country
     *
     * @return the value of wx_user_info.country
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.headimgurl
     *
     * @return the value of wx_user_info.headimgurl
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.subscribe
     *
     * @return the value of wx_user_info.subscribe
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public Integer getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.parentId
     *
     * @return the value of wx_user_info.parentId
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.ticket
     *
     * @return the value of wx_user_info.ticket
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public String getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.createTime
     *
     * @return the value of wx_user_info.createTime
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.commission
     *
     * @return the value of wx_user_info.commission
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    public Integer getCommission() {
        return commission;
    }
}