package com.core.model;

public class WxUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.user_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.open_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.nickname
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.sex
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.province
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.city
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.country
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_info.headimgurl
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String headimgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public WxUserInfo(Integer userId, String openId, String nickname, Integer sex, String province, String city, String country, String headimgurl) {
        this.userId = userId;
        this.openId = openId;
        this.nickname = nickname;
        this.sex = sex;
        this.province = province;
        this.city = city;
        this.country = country;
        this.headimgurl = headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.user_id
     *
     * @return the value of wx_user_info.user_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.open_id
     *
     * @return the value of wx_user_info.open_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.nickname
     *
     * @return the value of wx_user_info.nickname
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.sex
     *
     * @return the value of wx_user_info.sex
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.province
     *
     * @return the value of wx_user_info.province
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.city
     *
     * @return the value of wx_user_info.city
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.country
     *
     * @return the value of wx_user_info.country
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_info.headimgurl
     *
     * @return the value of wx_user_info.headimgurl
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getHeadimgurl() {
        return headimgurl;
    }
}