package com.core.model;

public class WxUserAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_address.user_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private Integer userId;

    public WxUserAddress() {
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public void setCounty(String county) {
        this.county = county;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_address.province
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_address.city
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_address.county
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_address.address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_address.receiver
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_address.mobile_phone
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    private String mobilePhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public WxUserAddress(Integer userId, String province, String city, String county, String address, String receiver, String mobilePhone) {
        this.userId = userId;
        this.province = province;
        this.city = city;
        this.county = county;
        this.address = address;
        this.receiver = receiver;
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_address.user_id
     *
     * @return the value of wx_user_address.user_id
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_address.province
     *
     * @return the value of wx_user_address.province
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_address.city
     *
     * @return the value of wx_user_address.city
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_address.county
     *
     * @return the value of wx_user_address.county
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_address.address
     *
     * @return the value of wx_user_address.address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_address.receiver
     *
     * @return the value of wx_user_address.receiver
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_address.mobile_phone
     *
     * @return the value of wx_user_address.mobile_phone
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    public String getMobilePhone() {
        return mobilePhone;
    }
}