package com.core.model;

public class WxUserExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_ext.USER_ID
     *
     * @mbggenerated Mon Nov 16 15:11:41 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_ext.EXT_KEY
     *
     * @mbggenerated Mon Nov 16 15:11:41 CST 2015
     */
    private String extKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user_ext.EXT_VALUE
     *
     * @mbggenerated Mon Nov 16 15:11:41 CST 2015
     */
    private String extValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_ext
     *
     * @mbggenerated Mon Nov 16 15:11:41 CST 2015
     */
    public WxUserExt(Integer userId, String extKey, String extValue) {
        this.userId = userId;
        this.extKey = extKey;
        this.extValue = extValue;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public void setExtKey(String extKey) {
        this.extKey = extKey;
    }

    public void setExtValue(String extValue) {
        this.extValue = extValue;
    }

    public WxUserExt() {

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_ext.USER_ID
     *
     * @return the value of wx_user_ext.USER_ID
     *
     * @mbggenerated Mon Nov 16 15:11:41 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_ext.EXT_KEY
     *
     * @return the value of wx_user_ext.EXT_KEY
     *
     * @mbggenerated Mon Nov 16 15:11:41 CST 2015
     */
    public String getExtKey() {
        return extKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user_ext.EXT_VALUE
     *
     * @return the value of wx_user_ext.EXT_VALUE
     *
     * @mbggenerated Mon Nov 16 15:11:41 CST 2015
     */
    public String getExtValue() {
        return extValue;
    }
}