package com.core.dao;

import com.core.model.SysUser;
import com.core.model.SysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

@Repository
public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int countByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int deleteByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from sys_user",
        "where USER_ID = #{userId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sys_user (USER_ID, USER_NAME, ",
        "USER_LOGIN_NAME, EMAIL, ",
        "MOBILE_PHONE, USER_STATUS, ",
        "USER_TYPE, CREATER, ",
        "CREATE_TIME, UPDATER, ",
        "UPDATE_TIME, LOGIN_PWD, ",
        "CHANGE_TIME, PWD_ERR_TIME)",
        "values (#{userId,jdbcType=INTEGER}, #{userName,jdbcType=VARCHAR}, ",
        "#{userLoginName,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{mobilePhone,jdbcType=VARCHAR}, #{userStatus,jdbcType=VARCHAR}, ",
        "#{userType,jdbcType=VARCHAR}, #{creater,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updater,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=DATE}, #{loginPwd,jdbcType=VARCHAR}, ",
        "#{changeTime,jdbcType=DATE}, #{pwdErrTime,jdbcType=INTEGER})"
    })
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    List<SysUser> selectByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "USER_ID, USER_NAME, USER_LOGIN_NAME, EMAIL, MOBILE_PHONE, USER_STATUS, USER_TYPE, ",
        "CREATER, CREATE_TIME, UPDATER, UPDATE_TIME, LOGIN_PWD, CHANGE_TIME, PWD_ERR_TIME",
        "from sys_user",
        "where USER_ID = #{userId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    SysUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    @Update({
        "update sys_user",
        "set USER_NAME = #{userName,jdbcType=VARCHAR},",
          "USER_LOGIN_NAME = #{userLoginName,jdbcType=VARCHAR},",
          "EMAIL = #{email,jdbcType=VARCHAR},",
          "MOBILE_PHONE = #{mobilePhone,jdbcType=VARCHAR},",
          "USER_STATUS = #{userStatus,jdbcType=VARCHAR},",
          "USER_TYPE = #{userType,jdbcType=VARCHAR},",
          "CREATER = #{creater,jdbcType=INTEGER},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATER = #{updater,jdbcType=INTEGER},",
          "UPDATE_TIME = #{updateTime,jdbcType=DATE},",
          "LOGIN_PWD = #{loginPwd,jdbcType=VARCHAR},",
          "CHANGE_TIME = #{changeTime,jdbcType=DATE},",
          "PWD_ERR_TIME = #{pwdErrTime,jdbcType=INTEGER}",
        "where USER_ID = #{userId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SysUser record);
}