package com.core.dao;

import com.core.model.TWxSubs;
import com.core.model.TWxSubsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

@Repository
public interface TWxSubsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_subs
     *
     * @mbggenerated
     */
    int countByExample(TWxSubsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_subs
     *
     * @mbggenerated
     */
    int deleteByExample(TWxSubsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_subs
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_wx_subs",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_subs
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_wx_subs (ID, APPID, ",
        "OPENID, SUBSCRIBETIME, ",
        "NICKNAME, USER_LOGIN_NAME, ",
        "DEPT_CODE, SEX, CITY_CODE, ",
        "COUNTRY_CODE, PROVINCE_CODE, ",
        "LANGUAGE, HEADIMGURL, ",
        "UNIONID, CREATE_TIME, ",
        "UPDATE_TIME, \" PARENT_ID\")",
        "values (#{id,jdbcType=VARCHAR}, #{appid,jdbcType=VARCHAR}, ",
        "#{openid,jdbcType=VARCHAR}, #{subscribetime,jdbcType=TIMESTAMP}, ",
        "#{nickname,jdbcType=VARCHAR}, #{userLoginName,jdbcType=VARCHAR}, ",
        "#{deptCode,jdbcType=VARCHAR}, #{sex,jdbcType=VARCHAR}, #{cityCode,jdbcType=VARCHAR}, ",
        "#{countryCode,jdbcType=VARCHAR}, #{provinceCode,jdbcType=VARCHAR}, ",
        "#{language,jdbcType=VARCHAR}, #{headimgurl,jdbcType=VARCHAR}, ",
        "#{unionid,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{parentId,jdbcType=VARCHAR})"
    })
    int insert(TWxSubs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_subs
     *
     * @mbggenerated
     */
    int insertSelective(TWxSubs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_subs
     *
     * @mbggenerated
     */
    List<TWxSubs> selectByExample(TWxSubsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_subs
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, APPID, OPENID, SUBSCRIBETIME, NICKNAME, USER_LOGIN_NAME, DEPT_CODE, SEX, ",
        "CITY_CODE, COUNTRY_CODE, PROVINCE_CODE, LANGUAGE, HEADIMGURL, UNIONID, CREATE_TIME, ",
        "UPDATE_TIME, \" PARENT_ID\"",
        "from t_wx_subs",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    TWxSubs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_subs
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TWxSubs record, @Param("example") TWxSubsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_subs
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TWxSubs record, @Param("example") TWxSubsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_subs
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TWxSubs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_subs
     *
     * @mbggenerated
     */
    @Update({
        "update t_wx_subs",
        "set APPID = #{appid,jdbcType=VARCHAR},",
          "OPENID = #{openid,jdbcType=VARCHAR},",
          "SUBSCRIBETIME = #{subscribetime,jdbcType=TIMESTAMP},",
          "NICKNAME = #{nickname,jdbcType=VARCHAR},",
          "USER_LOGIN_NAME = #{userLoginName,jdbcType=VARCHAR},",
          "DEPT_CODE = #{deptCode,jdbcType=VARCHAR},",
          "SEX = #{sex,jdbcType=VARCHAR},",
          "CITY_CODE = #{cityCode,jdbcType=VARCHAR},",
          "COUNTRY_CODE = #{countryCode,jdbcType=VARCHAR},",
          "PROVINCE_CODE = #{provinceCode,jdbcType=VARCHAR},",
          "LANGUAGE = #{language,jdbcType=VARCHAR},",
          "HEADIMGURL = #{headimgurl,jdbcType=VARCHAR},",
          "UNIONID = #{unionid,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP},",
          "\" PARENT_ID\" = #{parentId,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TWxSubs record);
}