package com.core.dao;

import com.core.model.ViewCache;
import com.core.model.ViewCacheExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ViewCacheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cache
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    int countByExample(ViewCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cache
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    int deleteByExample(ViewCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cache
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    @Insert({
        "insert into view_cache (P_KEY, p_value, ",
        "p_desc, P_P_VALUE)",
        "values (#{pKey,jdbcType=VARCHAR}, #{pValue,jdbcType=DECIMAL}, ",
        "#{pDesc,jdbcType=VARCHAR}, #{pPValue,jdbcType=CHAR})"
    })
    int insert(ViewCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cache
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    int insertSelective(ViewCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cache
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    List<ViewCache> selectByExample(ViewCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cache
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    int updateByExampleSelective(@Param("record") ViewCache record, @Param("example") ViewCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_cache
     *
     * @mbggenerated Thu Nov 12 16:33:12 CST 2015
     */
    int updateByExample(@Param("record") ViewCache record, @Param("example") ViewCacheExample example);
}