package com.core.dao;

import com.core.model.WebsiteArea;
import com.core.model.WebsiteAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

@Repository
public interface WebsiteAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_area
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    int countByExample(WebsiteAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_area
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    int deleteByExample(WebsiteAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_area
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    @Delete({
        "delete from website_area",
        "where area_id = #{areaId,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_area
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    @Insert({
        "insert into website_area (area_id, area_name, ",
        "parent_id, area_level, ",
        "status, sort_id)",
        "values (#{areaId,jdbcType=DECIMAL}, #{areaName,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=DECIMAL}, #{areaLevel,jdbcType=DECIMAL}, ",
        "#{status,jdbcType=DECIMAL}, #{sortId,jdbcType=INTEGER})"
    })
    int insert(WebsiteArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_area
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    int insertSelective(WebsiteArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_area
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    List<WebsiteArea> selectByExample(WebsiteAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_area
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    @Select({
        "select",
        "area_id, area_name, parent_id, area_level, status, sort_id",
        "from website_area",
        "where area_id = #{areaId,jdbcType=DECIMAL}"
    })
    @ResultMap("BaseResultMap")
    WebsiteArea selectByPrimaryKey(Long areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_area
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    int updateByExampleSelective(@Param("record") WebsiteArea record, @Param("example") WebsiteAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_area
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    int updateByExample(@Param("record") WebsiteArea record, @Param("example") WebsiteAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_area
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    int updateByPrimaryKeySelective(WebsiteArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_area
     *
     * @mbggenerated Thu Nov 12 16:18:40 CST 2015
     */
    @Update({
        "update website_area",
        "set area_name = #{areaName,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=DECIMAL},",
          "area_level = #{areaLevel,jdbcType=DECIMAL},",
          "status = #{status,jdbcType=DECIMAL},",
          "sort_id = #{sortId,jdbcType=INTEGER}",
        "where area_id = #{areaId,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(WebsiteArea record);
}