package com.core.dao;

import com.core.model.WxMerInfo;
import com.core.model.WxMerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface WxMerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int countByExample(WxMerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int deleteByExample(WxMerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Delete({
        "delete from wx_mer_info",
        "where gds_id = #{gdsId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer gdsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Insert({
        "insert into wx_mer_info (gds_id, gds_title, ",
        "gds_description, gds_price, ",
        "pic_url, url, gds_count, ",
        "order_id, gds_url, ",
        "gds_detail)",
        "values (#{gdsId,jdbcType=INTEGER}, #{gdsTitle,jdbcType=VARCHAR}, ",
        "#{gdsDescription,jdbcType=VARCHAR}, #{gdsPrice,jdbcType=INTEGER}, ",
        "#{picUrl,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, #{gdsCount,jdbcType=INTEGER}, ",
        "#{orderId,jdbcType=INTEGER}, #{gdsUrl,jdbcType=VARCHAR}, ",
        "#{gdsDetail,jdbcType=VARCHAR})"
    })
    int insert(WxMerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int insertSelective(WxMerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    List<WxMerInfo> selectByExample(WxMerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Select({
        "select",
        "gds_id, gds_title, gds_description, gds_price, pic_url, url, gds_count, order_id, ",
        "gds_url, gds_detail",
        "from wx_mer_info",
        "where gds_id = #{gdsId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    WxMerInfo selectByPrimaryKey(Integer gdsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") WxMerInfo record, @Param("example") WxMerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int updateByExample(@Param("record") WxMerInfo record, @Param("example") WxMerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int updateByPrimaryKeySelective(WxMerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Update({
        "update wx_mer_info",
        "set gds_title = #{gdsTitle,jdbcType=VARCHAR},",
          "gds_description = #{gdsDescription,jdbcType=VARCHAR},",
          "gds_price = #{gdsPrice,jdbcType=INTEGER},",
          "pic_url = #{picUrl,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "gds_count = #{gdsCount,jdbcType=INTEGER},",
          "order_id = #{orderId,jdbcType=INTEGER},",
          "gds_url = #{gdsUrl,jdbcType=VARCHAR},",
          "gds_detail = #{gdsDetail,jdbcType=VARCHAR}",
        "where gds_id = #{gdsId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WxMerInfo record);
}