package com.core.dao;

import com.core.model.WxMerPic;
import com.core.model.WxMerPicExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

@Repository
public interface WxMerPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_pic
     *
     * @mbggenerated Sun Nov 08 14:27:49 CST 2015
     */
    int countByExample(WxMerPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_pic
     *
     * @mbggenerated Sun Nov 08 14:27:49 CST 2015
     */
    int deleteByExample(WxMerPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_pic
     *
     * @mbggenerated Sun Nov 08 14:27:49 CST 2015
     */
    @Delete({
        "delete from wx_mer_pic",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_pic
     *
     * @mbggenerated Sun Nov 08 14:27:49 CST 2015
     */
    @Insert({
        "insert into wx_mer_pic (id, gds_id, ",
        "pic_url)",
        "values (#{id,jdbcType=INTEGER}, #{gdsId,jdbcType=INTEGER}, ",
        "#{picUrl,jdbcType=VARCHAR})"
    })
    int insert(WxMerPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_pic
     *
     * @mbggenerated Sun Nov 08 14:27:49 CST 2015
     */
    int insertSelective(WxMerPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_pic
     *
     * @mbggenerated Sun Nov 08 14:27:49 CST 2015
     */
    List<WxMerPic> selectByExample(WxMerPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_pic
     *
     * @mbggenerated Sun Nov 08 14:27:49 CST 2015
     */
    @Select({
        "select",
        "id, gds_id, pic_url",
        "from wx_mer_pic",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    WxMerPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_pic
     *
     * @mbggenerated Sun Nov 08 14:27:49 CST 2015
     */
    int updateByExampleSelective(@Param("record") WxMerPic record, @Param("example") WxMerPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_pic
     *
     * @mbggenerated Sun Nov 08 14:27:49 CST 2015
     */
    int updateByExample(@Param("record") WxMerPic record, @Param("example") WxMerPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_pic
     *
     * @mbggenerated Sun Nov 08 14:27:49 CST 2015
     */
    int updateByPrimaryKeySelective(WxMerPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mer_pic
     *
     * @mbggenerated Sun Nov 08 14:27:49 CST 2015
     */
    @Update({
        "update wx_mer_pic",
        "set gds_id = #{gdsId,jdbcType=INTEGER},",
          "pic_url = #{picUrl,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WxMerPic record);
}