package com.core.dao;

import com.core.model.WxOrderInfo;
import com.core.model.WxOrderInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface WxOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int countByExample(WxOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int deleteByExample(WxOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Delete({
        "delete from wx_order_info",
        "where order_id = #{orderId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Insert({
        "insert into wx_order_info (order_id, gds_id, ",
        "gds_amount, gds_count, ",
        "status, pay_type, ",
        "pay_status, create_time, ",
        "remark, user_id)",
        "values (#{orderId,jdbcType=BIGINT}, #{gdsId,jdbcType=INTEGER}, ",
        "#{gdsAmount,jdbcType=INTEGER}, #{gdsCount,jdbcType=INTEGER}, ",
        "#{status,jdbcType=INTEGER}, #{payType,jdbcType=VARCHAR}, ",
        "#{payStatus,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{remark,jdbcType=VARCHAR}, #{userId,jdbcType=INTEGER})"
    })
    int insert(WxOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int insertSelective(WxOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    List<WxOrderInfo> selectByExample(WxOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Select({
        "select",
        "order_id, gds_id, gds_amount, gds_count, status, pay_type, pay_status, create_time, ",
        "remark, user_id",
        "from wx_order_info",
        "where order_id = #{orderId,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    WxOrderInfo selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") WxOrderInfo record, @Param("example") WxOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int updateByExample(@Param("record") WxOrderInfo record, @Param("example") WxOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int updateByPrimaryKeySelective(WxOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Update({
        "update wx_order_info",
        "set gds_id = #{gdsId,jdbcType=INTEGER},",
          "gds_amount = #{gdsAmount,jdbcType=INTEGER},",
          "gds_count = #{gdsCount,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER},",
          "pay_type = #{payType,jdbcType=VARCHAR},",
          "pay_status = #{payStatus,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=INTEGER}",
        "where order_id = #{orderId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(WxOrderInfo record);
}