package com.core.dao;

import com.core.model.WxOrderAddress;
import com.core.model.WxOrderAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface WxOrderAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int countByExample(WxOrderAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int deleteByExample(WxOrderAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Insert({
        "insert into wx_order_address (user_id, order_id, ",
        "province, city, ",
        "county, address, ",
        "receiver, mobile_phone)",
        "values (#{userId,jdbcType=INTEGER}, #{orderId,jdbcType=BIGINT}, ",
        "#{province,jdbcType=VARCHAR}, #{city,jdbcType=VARCHAR}, ",
        "#{county,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{receiver,jdbcType=VARCHAR}, #{mobilePhone,jdbcType=VARCHAR})"
    })
    int insert(WxOrderAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int insertSelective(WxOrderAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    List<WxOrderAddress> selectByExample(WxOrderAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") WxOrderAddress record, @Param("example") WxOrderAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_order_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int updateByExample(@Param("record") WxOrderAddress record, @Param("example") WxOrderAddressExample example);
}