package com.core.dao;

import com.core.model.WxUserInfo;
import com.core.model.WxUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface WxUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int countByExample(WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int deleteByExample(WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Delete({
        "delete from wx_user_info",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Insert({
        "insert into wx_user_info (user_id, open_id, ",
        "nickname, sex, province, ",
        "city, country, headimgurl)",
        "values (#{userId,jdbcType=INTEGER}, #{openId,jdbcType=VARCHAR}, ",
        "#{nickname,jdbcType=VARCHAR}, #{sex,jdbcType=INTEGER}, #{province,jdbcType=VARCHAR}, ",
        "#{city,jdbcType=VARCHAR}, #{country,jdbcType=VARCHAR}, #{headimgurl,jdbcType=VARCHAR})"
    })
    int insert(WxUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int insertSelective(WxUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    List<WxUserInfo> selectByExample(WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Select({
        "select",
        "user_id, open_id, nickname, sex, province, city, country, headimgurl",
        "from wx_user_info",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    WxUserInfo selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") WxUserInfo record, @Param("example") WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int updateByExample(@Param("record") WxUserInfo record, @Param("example") WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int updateByPrimaryKeySelective(WxUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Update({
        "update wx_user_info",
        "set open_id = #{openId,jdbcType=VARCHAR},",
          "nickname = #{nickname,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=INTEGER},",
          "province = #{province,jdbcType=VARCHAR},",
          "city = #{city,jdbcType=VARCHAR},",
          "country = #{country,jdbcType=VARCHAR},",
          "headimgurl = #{headimgurl,jdbcType=VARCHAR}",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WxUserInfo record);
}