package com.core.dao;

import com.core.model.WxUserInfo;
import com.core.model.WxUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

@Repository
public interface WxUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    int countByExample(WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    int deleteByExample(WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    @Delete({
        "delete from wx_user_info",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    @Insert({
        "insert into wx_user_info (user_id, open_id, ",
        "nickname, sex, province, ",
        "city, country, headimgurl, ",
        "subscribe, parentId, ",
        "ticket, createTime, ",
        "commission)",
        "values (#{userId,jdbcType=INTEGER}, #{openId,jdbcType=VARCHAR}, ",
        "#{nickname,jdbcType=VARCHAR}, #{sex,jdbcType=INTEGER}, #{province,jdbcType=VARCHAR}, ",
        "#{city,jdbcType=VARCHAR}, #{country,jdbcType=VARCHAR}, #{headimgurl,jdbcType=VARCHAR}, ",
        "#{subscribe,jdbcType=INTEGER}, #{parentid,jdbcType=INTEGER}, ",
        "#{ticket,jdbcType=VARCHAR}, #{createtime,jdbcType=TIMESTAMP}, ",
        "#{commission,jdbcType=INTEGER})"
    })
    int insert(WxUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    int insertSelective(WxUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    List<WxUserInfo> selectByExample(WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    @Select({
        "select",
        "user_id, open_id, nickname, sex, province, city, country, headimgurl, subscribe, ",
        "parentId, ticket, createTime, commission",
        "from wx_user_info",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    WxUserInfo selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") WxUserInfo record, @Param("example") WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    int updateByExample(@Param("record") WxUserInfo record, @Param("example") WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    int updateByPrimaryKeySelective(WxUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_info
     *
     * @mbggenerated Sun Nov 15 13:02:53 CST 2015
     */
    @Update({
        "update wx_user_info",
        "set open_id = #{openId,jdbcType=VARCHAR},",
          "nickname = #{nickname,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=INTEGER},",
          "province = #{province,jdbcType=VARCHAR},",
          "city = #{city,jdbcType=VARCHAR},",
          "country = #{country,jdbcType=VARCHAR},",
          "headimgurl = #{headimgurl,jdbcType=VARCHAR},",
          "subscribe = #{subscribe,jdbcType=INTEGER},",
          "parentId = #{parentid,jdbcType=INTEGER},",
          "ticket = #{ticket,jdbcType=VARCHAR},",
          "createTime = #{createtime,jdbcType=TIMESTAMP},",
          "commission = #{commission,jdbcType=INTEGER}",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WxUserInfo record);

   List<Integer> selectSons(@Param("id") Integer id);
    List<Integer> selectGrandSons(@Param("id") Integer id);
}