package com.core.dao;

import com.core.model.WxUserAddress;
import com.core.model.WxUserAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface WxUserAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int countByExample(WxUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int deleteByExample(WxUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    @Insert({
        "insert into wx_user_address (user_id, province, ",
        "city, county, address, ",
        "receiver, mobile_phone)",
        "values (#{userId,jdbcType=INTEGER}, #{province,jdbcType=VARCHAR}, ",
        "#{city,jdbcType=VARCHAR}, #{county,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{receiver,jdbcType=VARCHAR}, #{mobilePhone,jdbcType=VARCHAR})"
    })
    int insert(WxUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int insertSelective(WxUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    List<WxUserAddress> selectByExample(WxUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") WxUserAddress record, @Param("example") WxUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_address
     *
     * @mbggenerated Tue Nov 03 21:32:31 CST 2015
     */
    int updateByExample(@Param("record") WxUserAddress record, @Param("example") WxUserAddressExample example);
}